#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <math.h>
#include <time.h>
#include "gpu_mapping.h"
#include <unistd.h>
#include "multipole_struct.h"
#include "error.h"
#include "gravity_derivatives.h"

#include "gpu_functions.h"

/**
 * @brief Find the smallest distance dx along one axis within a box of size
 * box_size - GPU version
 *
 * This macro evaluates its arguments exactly once.
 *
 * Only wraps once. If dx > 2b, the returned value will be larger than b.
 * Similarly for dx < -b.
 *
 */
__device__ float nearestf1(
    float dx, const float box_size) {

    return ((dx > 0.5 * box_size)
              ? (dx - box_size)
              : ((dx < -0.5 * box_size) ? (dx + box_size) : dx));
}

/**
 * @brief Computes the gravity softening kernel for the forces. - GPU version
 *
 * This functions assumes 0 < u < 1.
 *
 * @param u The ratio of the distance to the spline softening length $u = x/H$.
 */
__device__ float grav_force_eval(const float u){
  float W;
#ifdef GADGET2_SOFTENING_CORRECTION
  float W_f_less = 10.6666667f + u * u * (32.f * u - 38.4f);
  float W_f_more = 21.3333333f - 48.f * u + 38.4f * u * u - 10.6666667f * u * u * u - 0.06666667f / (u * u * u);
  W = abs(round(round(round(u)/u)-1))*W_f_less + round(round(u)/u)*W_f_more;
#else

  /* W(u) = 21u^5 - 90u^4 + 140u^3 - 84u^2 + 14 */
  W = 21.f * u - 90.f;
  W = W * u + 140.f;
  W = W * u - 84.f;
  W = W * u;
  W = W * u + 14.f;
#endif
  return W;
}

/**
 * @brief Computes the gravity softening kernel for the potential. - GPU version
 *
 * This functions assumes 0 < u < 1.
 *
 * @param u The ratio of the distance to the spline softening length $u = x/H$.
 */
__device__ float grav_pot_eval(const float u) {
  float W;
#ifdef GADGET2_SOFTENING_CORRECTION
  float W_pot_less = -2.8f + u * u * (5.333333333333f + u * u * (6.4f * u - 9.6f));
  float W_pot_more = -3.2f + 0.066666666667f / u + u * u * (10.666666666667f + u * (-16.f + u * (9.6f - 2.133333333333f * u)));
  W = abs(round(round(round(u)/u)-1))*W_pot_less + round(round(u)/u)*W_pot_more;
#else

  /* W(u) = 3u^7 - 15u^6 + 28u^5 - 21u^4 + 7u^2 - 3 */
  W = 3.f * u - 15.f;
  W = W * u + 28.f;
  W = W * u - 21.f;
  W = W * u;
  W = W * u + 7.f;
  W = W * u;
  W = W * u - 3.f;
#endif
  return W;
}

/**
 * @brief Computes the long-range correction terms for the potential and
 * force calculations due to the mesh truncation. - GPU version
 *
 * We use an approximation to the erfc() that gives a *relative* accuracy
 * for the potential tem of 3.4e-3 and 2.4e-4 for the force term over the
 * range [0, 5] of r_over_r_s.
 * The accuracy is much better in the range [0, 2] (6e-5 and 2e-5 respectively).
 *
 * @param r_over_r_s The ratio of the distance to the FFT cell scale \f$u =
 * r/r_s\f$.
 * @param corr_f (return) The correction for the force term.
 * @param corr_pot (return) The correction for the potential term.
 */
__device__ void long_grav_eval(const float r_over_r_s, float *corr_f, float *corr_pot){
#ifdef GADGET2_LONG_RANGE_CORRECTION

  const float two_over_sqrt_pi = ((float)M_2_SQRTPI);

  const float u = 0.5f * r_over_r_s;
  const float u2 = u * u;
  const float exp_u2 = expf(-u2);

  /* Compute erfcf(u) using eq. 7.1.26 of
   * Abramowitz & Stegun, 1972.
   *
   * This has a *relative* error of less than 3.4e-3 over
   * the range of interest (0 < u < 5)\
   *
   * This is a good approximation to use since we already
   * need exp(-u2) */

  const float t = 1.f / (1.f + 0.3275911f * u);

  const float a1 = 0.254829592f;
  const float a2 = -0.284496736f;
  const float a3 = 1.421413741f;
  const float a4 = -1.453152027;
  const float a5 = 1.061405429f;

  /* a1 * t + a2 * t^2 + a3 * t^3 + a4 * t^4 + a5 * t^5 */
  float a = a5 * t + a4;
  a = a * t + a3;
  a = a * t + a2;
  a = a * t + a1;
  a = a * t;

  const float erfc_u = a * exp_u2;

  *corr_pot = erfc_u;
  *corr_f = erfc_u + two_over_sqrt_pi * u * exp_u2;

#else
  const float x = 2.f * r_over_r_s;
  const float exp_x = expf(x);  // good_approx_expf(x);
  const float alpha = 1.f / (1.f + exp_x);

  /* We want 2 - 2 exp(x) * alpha */
  float W = 1.f - alpha * exp_x;
  W = W * 2.f;

  *corr_pot = W;

  /* We want 2*(x*alpha - x*alpha^2 - exp(x)*alpha + 1) */
  W = 1.f - alpha;
  W = W * x - exp_x;
  W = W * alpha + 1.f;
  W = W * 2.f;

  *corr_f = W;
#endif
}

/**
 * @brief Computes the intensity of the force at a point generated by a
 * point-mass. - GPU version
 *
 * The returned quantity needs to be multiplied by the distance vector to obtain
 * the force vector.
 *
 * @param r2 Square of the distance to the point-mass.
 * @param h2 Square of the softening length.
 * @param h_inv Inverse of the softening length.
 * @param h_inv3 Cube of the inverse of the softening length.
 * @param mass Mass of the point-mass.
 * @param f_ij (return) The force intensity.
 * @param pot_ij (return) The potential.
 */
__device__ void iact_grav_pp_full(const float r2, const float h2, const float h_inv, const float h_inv3, const float mass, float *f_ij, float *pot_ij) {

  /* Get the inverse distance */
  const float r_inv = rsqrtf(r2 + FLT_MIN);

  /* Should we soften ? */
  if (r2 >= h2) {

    /* Get Newtonian gravity */
    *f_ij = mass * r_inv * r_inv * r_inv;
    *pot_ij = -mass * r_inv;

  } else {

    const float r = r2 * r_inv;
    const float ui = r * h_inv;
    const float W_f_ij = grav_force_eval(ui);
    const float W_pot_ij = grav_pot_eval(ui);

    /* Get softened gravity */
    *f_ij = mass * h_inv3 * W_f_ij;
    *pot_ij = mass * h_inv * W_pot_ij;
  }
}

/**
 * @brief Computes the intensity of the force at a point generated by a
 * point-mass truncated for long-distance periodicity.
 *
 * The returned quantity needs to be multiplied by the distance vector to obtain
 * the force vector.
 *
 * @param r2 Square of the distance to the point-mass.
 * @param h2 Square of the softening length.
 * @param h_inv Inverse of the softening length.
 * @param h_inv3 Cube of the inverse of the softening length.
 * @param mass Mass of the point-mass.
 * @param r_s_inv Inverse of the mesh smoothing scale.
 * @param f_ij (return) The force intensity.
 * @param pot_ij (return) The potential.
 */
__device__ void iact_grav_pp_truncated(const float r2, const float h2, const float h_inv, const float h_inv3, const float mass, const float r_s_inv, float *f_ij, float *pot_ij){

  /* Get the inverse distance */
  const float r_inv = rsqrtf(r2 + FLT_MIN);
  const float r = r2 * r_inv;

  /* Should we soften ? */
  if (r2 >= h2) {
    
    /* Get Newtonian gravity */
    *f_ij = mass * r_inv * r_inv * r_inv;
    *pot_ij = -mass * r_inv;

  } else {

    const float ui = r * h_inv;
    const float W_f_ij = grav_force_eval(ui);
    const float W_pot_ij = grav_pot_eval(ui);

    /* Get softened gravity */
    *f_ij = mass * h_inv3 * W_f_ij;
    *pot_ij = mass * h_inv * W_pot_ij;
  }

  /* Get long-range correction */
  const float u_lr = r * r_s_inv;
  float corr_f_lr, corr_pot_lr;
  long_grav_eval(u_lr, &corr_f_lr, &corr_pot_lr);
  *f_ij *= corr_f_lr;
  *pot_ij *= corr_pot_lr;
}

/**
 * @brief Compute full self-cell P-P gravity interactions on the GPU.
 *
 * Each block processes one packed cell and accumulates direct particle-particle
 * interactions for the active particles in that cell.
 *
 * @param gravity_gpu_values_send_d Device input buffer for packed particles.
 * @param gravity_gpu_values_recv_d Device output buffer for accelerations and potential.
 * @param r_s_inv Inverse splitting scale (unused for the full interaction path).
 * @param gcount_i Number of particles in the cell.
 * @param gcount_padded_i Padded particle count in the cell.
 * @param periodic Whether periodic boundary conditions are enabled.
 * @param ci_active Whether the packed cell is active.
 * @param max_r_decision Whether the full interaction path should be used.
 * @param ncells Number of packed cells in the batch.
 * @param max_cell_size Maximum number of particles per packed cell.
 */
__global__ void doself_grav_pp_full_new_refactor(struct gravity_gpu_values_send *gravity_gpu_values_send_d, struct gravity_gpu_values_recv *gravity_gpu_values_recv_d, float r_s_inv, const int gcount_i, const int gcount_padded_i, const int periodic, int ci_active, int max_r_decision, int ncells, int max_cell_size) {

	int cell = blockIdx.x;
	if (cell >= ncells)
		return;
	
	int cell_space = cell*max_cell_size;
	int counts = gravity_gpu_values_send_d[cell_space].flags0.z;
	
	float factor1 = gravity_gpu_values_send_d[cell_space].flags0.w*abs(periodic-1);
	float factor2 = gravity_gpu_values_send_d[cell_space].flags0.w*periodic*max_r_decision;
		
	int pid = blockIdx.y*blockDim.x +threadIdx.x;
	if (pid >= counts) 
		return;
		
	/*values for particle*/
	float xi = gravity_gpu_values_send_d[cell_space + pid].values_i.x;
  	float yi = gravity_gpu_values_send_d[cell_space + pid].values_i.y;
  	float zi = gravity_gpu_values_send_d[cell_space + pid].values_i.z;
  	float hi = gravity_gpu_values_send_d[cell_space + pid].values_i.w;	

	/* Local accumulators for the acceleration and potential */
	float a_x = 0.f, a_y = 0.f, a_z = 0.f, pot = 0.f;
	
	/*extern __shared__ gravity_gpu_values_send send[];

  	for (int i0 = 0; i0 < counts; i0 += blockDim.x) {

    		int i = i0 + threadIdx.x;
    		if (i < counts) send[threadIdx.x] = gravity_gpu_values_send_d[cell_space + i];
    		__syncthreads();

   	int tile = min(blockDim.x, counts - i0);
   	
   	for (int j = 0; j < tile; j++) {
		int pjd = i0 + j;*/
	
	/* Loop over every other particle in the cell. */
	for (int pjd = 0; pjd < counts; pjd++) {
		
	      /* No self interaction */
	      if (pid == pjd) continue;
	      
	      const gravity_gpu_values_send pj = gravity_gpu_values_send_d[cell_space + pjd];

	      /* Get info about j */
	      const float mass_i = pj.mass.x;

	      /* Compute the pairwise (square) distance. */
	      /* Note: no need for periodic wrapping inside a cell */
	      float dx = pj.values_i.x - xi;
	      float dy = pj.values_i.y - yi;
	      float dz = pj.values_i.z - zi;

	      const float r2 = dx * dx + dy * dy + dz * dz;

	      /* Pick the maximal softening length of i and j */
	      const float h = max(hi, pj.values_i.w);
	      const float h2 = h * h;
	      const float h_inv = 1.f / h;
	      const float h_inv_3 = h_inv * h_inv * h_inv;

	      /* Interact! */
	      float f_ij, pot_ij;
	      iact_grav_pp_full(r2, h2, h_inv, h_inv_3, mass_i, &f_ij, &pot_ij);

	      /* Store it back */
	      a_x += f_ij * dx;
	      a_y += f_ij * dy;
	      a_z += f_ij * dz;
	      pot += pot_ij;

	    }
	    //__syncthreads();
	    
	  
	int act = 0;
	if (gravity_gpu_values_send_d[pid+cell_space].flags0.x > 0)
		act = 1;
	  
	  gravity_gpu_values_recv_d[cell_space + pid].values_i.x += a_x*act*(factor1+factor2);
	  gravity_gpu_values_recv_d[cell_space + pid].values_i.y += a_y*act*(factor1+factor2);
	  gravity_gpu_values_recv_d[cell_space + pid].values_i.z += a_z*act*(factor1+factor2);
	  gravity_gpu_values_recv_d[cell_space + pid].values_i.w += pot*act*(factor1+factor2);
}

/**
 * @brief Compute truncated self-cell P-P gravity interactions on the GPU.
 *
 * Each block processes one packed cell and accumulates direct particle-particle
 * interactions for the active particles in that cell.
 *
 * @param gravity_gpu_values_send_d Device input buffer for packed particles.
 * @param gravity_gpu_values_recv_d Device output buffer for accelerations and potential.
 * @param r_s_inv Inverse splitting scale for long-range correction.
 * @param gcount_i Number of particles in the cell.
 * @param gcount_padded_i Padded particle count in the cell.
 * @param periodic Whether periodic boundary conditions are enabled.
 * @param ci_active Whether the packed cell is active.
 * @param max_r_decision Whether the truncated interaction path should be used.
 * @param ncells Number of packed cells in the batch.
 * @param max_cell_size Maximum number of particles per packed cell.
 */
//SELF PP TRUNCATED INTERACTIONS
__global__ void doself_grav_pp_truncated_new_refactor(struct gravity_gpu_values_send *gravity_gpu_values_send_d, struct gravity_gpu_values_recv *gravity_gpu_values_recv_d, float r_s_inv, const int gcount_i, const int gcount_padded_i, const int periodic, int ci_active, int max_r_decision, int ncells, int max_cell_size) {

	int cell = blockIdx.x;
	if (cell >= ncells)
		return;
	
	int cell_space = cell*max_cell_size;
	int counts = gravity_gpu_values_send_d[cell_space].flags0.z;
	//printf("counts: %i \n", counts);
	
	float factor = gravity_gpu_values_send_d[cell_space].flags0.w*(periodic ? 1.f : 0.f)*abs(max_r_decision-1);
	if (factor == 0)
		return;
		
	int pid = blockIdx.y*blockDim.x +threadIdx.x;
	if (pid >= counts) 
		return;
		
	/*values for particle*/
	float xi = gravity_gpu_values_send_d[cell_space + pid].values_i.x;
  	float yi = gravity_gpu_values_send_d[cell_space + pid].values_i.y;
  	float zi = gravity_gpu_values_send_d[cell_space + pid].values_i.z;
  	float hi = gravity_gpu_values_send_d[cell_space + pid].values_i.w;	

	/* Local accumulators for the acceleration and potential */
	float a_x = 0.f, a_y = 0.f, a_z = 0.f, pot = 0.f;
	
	/*extern __shared__ gravity_gpu_values_send send[];

  	for (int i0 = 0; i0 < counts; i0 += blockDim.x) {

    		int i = i0 + threadIdx.x;
    		if (i < counts) send[threadIdx.x] = gravity_gpu_values_send_d[cell_space + i];
    		__syncthreads();

   	int tile = min(blockDim.x, counts - i0);
   	
   	for (int j = 0; j < tile; j++) {
		int pjd = i0 + j;*/
	
	/* Loop over every other particle in the cell. */
	for (int pjd = 0; pjd < counts; pjd++) {
		
	      /* No self interaction */
	      if (pid == pjd) continue;
	      
	      const gravity_gpu_values_send pj = gravity_gpu_values_send_d[cell_space + pjd];

	      /* Get info about j */
	      const float mass_i = pj.mass.x;

	      /* Compute the pairwise (square) distance. */
	      /* Note: no need for periodic wrapping inside a cell */
	      float dx = pj.values_i.x - xi;
	      float dy = pj.values_i.y - yi;
	      float dz = pj.values_i.z - zi;

	      const float r2 = dx * dx + dy * dy + dz * dz;

	      /* Pick the maximal softening length of i and j */
	      const float h = max(hi, pj.values_i.w);
	      const float h2 = h * h;
	      const float h_inv = 1.f / h;
	      const float h_inv_3 = h_inv * h_inv * h_inv;

	      /* Interact! */
	      float f_ij, pot_ij;
	      iact_grav_pp_truncated(r2, h2, h_inv, h_inv_3, mass_i, r_s_inv,
		                            &f_ij, &pot_ij);

	      /* Store it back */
	      a_x += f_ij * dx;
	      a_y += f_ij * dy;
	      a_z += f_ij * dz;
	      pot += pot_ij;

	    }
	    //__syncthreads();
	    
	  
	  
	  gravity_gpu_values_recv_d[cell_space + pid].values_i.x = a_x*factor;
	  gravity_gpu_values_recv_d[cell_space + pid].values_i.y = a_y*factor;
	  gravity_gpu_values_recv_d[cell_space + pid].values_i.z = a_z*factor;
	  gravity_gpu_values_recv_d[cell_space + pid].values_i.w = pot*factor;
}

/**
 * @brief Compute full self-cell P-P gravity interactions using shared-memory tiling.
 *
 * This kernel is the tiled variant of the self-cell full-force interaction,
 * reusing source-particle data from shared memory to reduce global memory traffic.
 *
 * @param gravity_gpu_values_send_d Device input buffer for packed particles.
 * @param gravity_gpu_values_recv_d Device output buffer for accelerations and potential.
 * @param r_s_inv Inverse splitting scale (unused for the full interaction path).
 * @param gcount_i Number of particles in the cell.
 * @param gcount_padded_i Padded particle count in the cell.
 * @param periodic Whether periodic boundary conditions are enabled.
 * @param max_r_decision Whether the full interaction path should be used.
 * @param ncells Number of packed cells in the batch.
 */
__global__ void doself_grav_pp_full_new_refactor_tiled(
    const struct gravity_gpu_values_send *gravity_gpu_values_send_d,
    struct gravity_gpu_values_recv *gravity_gpu_values_recv_d,
    const int *counts_d,
    const int *offsets_d,
    const int *active_counts_d,
    const int *active_offsets_d,
    const int *active_index_d,
    const float *rmax_d,
    float r_s_inv,
    int periodic,
    float min_trunc,
    int ncells,
    int max_cell_size) {

  const int cell = blockIdx.x;
  if (cell >= ncells) return;

  const int counts = counts_d[cell];
  const int cell_offset = offsets_d[cell];
  if (counts <= 0) return;

  /* This kernel handles:
     - all non-periodic self cells
     - periodic self cells with rmax <= min_trunc */
  const int use_full = (!periodic) || (rmax_d[cell] <= min_trunc);
  if (!use_full) return;

  const float factor =
      gravity_gpu_values_send_d[cell_offset].flags0.w ? 1.f : 0.f;
  if (factor == 0.f) return;

  const int active_slot = blockIdx.y * blockDim.x + threadIdx.x;
  const int active_count = active_counts_d[cell];
  const int valid_pid = (active_slot < active_count);
  const int active_base = active_offsets_d[cell];
  const int local_pid =
    valid_pid ? active_index_d[active_base + active_slot] : 0;

  float xi = 0.f, yi = 0.f, zi = 0.f, hi = 0.f;

  if (valid_pid) {
    xi = gravity_gpu_values_send_d[cell_offset + local_pid].values_i.x;
    yi = gravity_gpu_values_send_d[cell_offset + local_pid].values_i.y;
    zi = gravity_gpu_values_send_d[cell_offset + local_pid].values_i.z;
    hi = gravity_gpu_values_send_d[cell_offset + local_pid].values_i.w;
  }

  float a_x = 0.f, a_y = 0.f, a_z = 0.f, pot = 0.f;

  extern __shared__ gravity_gpu_values_send send[];

  for (int i0 = 0; i0 < counts; i0 += blockDim.x) {
    const int i = i0 + threadIdx.x;
    if (i < counts) send[threadIdx.x] = gravity_gpu_values_send_d[cell_offset + i];
    __syncthreads();

    const int tile = min(blockDim.x, counts - i0);

    if (valid_pid) {
      for (int j = 0; j < tile; j++) {
        const int pjd = i0 + j;
        if (local_pid == pjd) continue;

        const gravity_gpu_values_send pj = send[j];
        const float mass_i = pj.mass.x;

        const float dx = pj.values_i.x - xi;
        const float dy = pj.values_i.y - yi;
        const float dz = pj.values_i.z - zi;

        const float r2 = dx * dx + dy * dy + dz * dz;
        const float h = max(hi, pj.values_i.w);
        const float h2 = h * h;
        const float h_inv = 1.f / h;
        const float h_inv_3 = h_inv * h_inv * h_inv;

        float f_ij, pot_ij;
        iact_grav_pp_full(r2, h2, h_inv, h_inv_3, mass_i, &f_ij, &pot_ij);

        a_x += f_ij * dx;
        a_y += f_ij * dy;
        a_z += f_ij * dz;
        pot += pot_ij;
      }
    }
    __syncthreads();
  }

  if (valid_pid) {
    const int out = active_base + active_slot;

	gravity_gpu_values_recv_d[out].values_i.x = a_x * factor;
	gravity_gpu_values_recv_d[out].values_i.y = a_y * factor;
	gravity_gpu_values_recv_d[out].values_i.z = a_z * factor;
	gravity_gpu_values_recv_d[out].values_i.w = pot * factor;
  }
}

/**
 * @brief Compute truncated self-cell P-P gravity interactions using shared-memory tiling.
 *
 * This kernel is the tiled variant of the self-cell truncated-force interaction,
 * reusing source-particle data from shared memory to reduce global memory traffic.
 *
 * @param gravity_gpu_values_send_d Device input buffer for packed particles.
 * @param gravity_gpu_values_recv_d Device output buffer for accelerations and potential.
 * @param r_s_inv Inverse splitting scale for long-range correction.
 * @param gcount_i Number of particles in the cell.
 * @param gcount_padded_i Padded particle count in the cell.
 * @param periodic Whether periodic boundary conditions are enabled.
 * @param max_r_decision Whether the truncated interaction path should be used.
 * @param ncells Number of packed cells in the batch.
 */
__global__ void doself_grav_pp_truncated_new_refactor_tiled(
    struct gravity_gpu_values_send *gravity_gpu_values_send_d,
    struct gravity_gpu_values_recv *gravity_gpu_values_recv_d,
    const int *counts_d,
    const int *offsets_d,
    const int *active_counts_d,
    const int *active_offsets_d,
    const int *active_index_d,
    const float *rmax_d,
    float r_s_inv,
    const int periodic,
    float min_trunc,
    int ncells) {

  const int cell = blockIdx.x;
  if (cell >= ncells) return;

  const int counts = counts_d[cell];
  const int cell_offset = offsets_d[cell];
  if (counts <= 0) return;

  /* This kernel handles only periodic self cells with rmax > min_trunc */
  const int use_truncated = periodic && (rmax_d[cell] > min_trunc);
  if (!use_truncated) return;

  const float factor =
      gravity_gpu_values_send_d[cell_offset].flags0.w ? 1.f : 0.f;
  if (factor == 0.f) return;

  const int active_slot = blockIdx.y * blockDim.x + threadIdx.x;
  const int active_count = active_counts_d[cell];
  const int valid_pid = (active_slot < active_count);
  const int active_base = active_offsets_d[cell];

  const int pid = valid_pid ? active_index_d[active_base + active_slot] : 0;

  float xi = 0.f, yi = 0.f, zi = 0.f, hi = 0.f;

  if (valid_pid) {
    xi = gravity_gpu_values_send_d[cell_offset + pid].values_i.x;
    yi = gravity_gpu_values_send_d[cell_offset + pid].values_i.y;
    zi = gravity_gpu_values_send_d[cell_offset + pid].values_i.z;
    hi = gravity_gpu_values_send_d[cell_offset + pid].values_i.w;
  }

  float a_x = 0.f, a_y = 0.f, a_z = 0.f, pot = 0.f;

  extern __shared__ gravity_gpu_values_send send[];

  for (int i0 = 0; i0 < counts; i0 += blockDim.x) {
    const int i = i0 + threadIdx.x;

    if (i < counts) {
      send[threadIdx.x] = gravity_gpu_values_send_d[cell_offset + i];
    }

    __syncthreads();

    const int tile = min(blockDim.x, counts - i0);

    if (valid_pid) {
      for (int j = 0; j < tile; j++) {
        const int pjd = i0 + j;
        if (pid == pjd) continue;

        const gravity_gpu_values_send pj = send[j];
        const float mass_i = pj.mass.x;

        const float dx = pj.values_i.x - xi;
        const float dy = pj.values_i.y - yi;
        const float dz = pj.values_i.z - zi;

        const float r2 = dx * dx + dy * dy + dz * dz;
        const float h = max(hi, pj.values_i.w);
        const float h2 = h * h;
        const float h_inv = 1.f / h;
        const float h_inv_3 = h_inv * h_inv * h_inv;

        float f_ij, pot_ij;
        iact_grav_pp_truncated(
            r2, h2, h_inv, h_inv_3, mass_i, r_s_inv, &f_ij, &pot_ij);

        a_x += f_ij * dx;
        a_y += f_ij * dy;
        a_z += f_ij * dz;
        pot += pot_ij;
      }
    }

    __syncthreads();
  }

  if (valid_pid) {
    const int out = active_base + active_slot;

    gravity_gpu_values_recv_d[out].values_i.x = a_x * factor;
    gravity_gpu_values_recv_d[out].values_i.y = a_y * factor;
    gravity_gpu_values_recv_d[out].values_i.z = a_z * factor;
    gravity_gpu_values_recv_d[out].values_i.w = pot * factor;
  }
}

/**
*
**/
__global__ void self_grav_pp_kernel_tiled(
    const struct gravity_gpu_values_send *__restrict__ gravity_gpu_values_send_d,
    struct gravity_gpu_values_recv *__restrict__ gravity_gpu_values_recv_d,
    const int *__restrict__ counts_d,
    const int *__restrict__ offsets_d,
    const int *__restrict__ active_counts_d,
    const int *__restrict__ active_offsets_d,
    const int *__restrict__ active_index_d,
    const float *__restrict__ rmax_d,
    float r_s_inv,
    const int periodic,
    float min_trunc,
    int ncells,
    int max_cell_size) {

  const int cell = blockIdx.x;
  if (cell >= ncells) return;

  const int counts = counts_d[cell];
  if (counts <= 0) return;

  const int active_count = active_counts_d[cell];
  if (active_count <= 0) return;

  const int cell_offset = offsets_d[cell];

  const float factor =
      gravity_gpu_values_send_d[cell_offset].flags0.w ? 1.f : 0.f;
  if (factor == 0.f) return;

  const int use_full = (!periodic) || (rmax_d[cell] <= min_trunc);

  const int active_slot = blockIdx.y * blockDim.x + threadIdx.x;
  const int valid_target = (active_slot < active_count);

  const int active_base = active_offsets_d[cell];
  int local_pid = 0;
  if (valid_target) {
    local_pid = active_index_d[active_base + active_slot];
  }

  float xi = 0.f, yi = 0.f, zi = 0.f, hi = 0.f;

  if (valid_target) {
    const gravity_gpu_values_send pi =
        gravity_gpu_values_send_d[cell_offset + local_pid];
    xi = pi.values_i.x;
    yi = pi.values_i.y;
    zi = pi.values_i.z;
    hi = pi.values_i.w;
  }

  float a_x = 0.f, a_y = 0.f, a_z = 0.f, pot = 0.f;

  extern __shared__ gravity_gpu_values_send send[];

  for (int i0 = 0; i0 < counts; i0 += blockDim.x) {
    const int i = i0 + threadIdx.x;
    if (i < counts) {
      send[threadIdx.x] = gravity_gpu_values_send_d[cell_offset + i];
    }
    __syncthreads();

    const int tile = min(blockDim.x, counts - i0);

    if (valid_target) {
      for (int j = 0; j < tile; j++) {
        const int src_local_pid = i0 + j;

        if (local_pid == src_local_pid) continue;

        const gravity_gpu_values_send pj = send[j];
        const float mass_j = pj.mass.y;

        const float dx = pj.values_j.x - xi;
        const float dy = pj.values_j.y - yi;
        const float dz = pj.values_j.z - zi;

        const float r2 = dx * dx + dy * dy + dz * dz;
        const float h = max(hi, pj.values_j.w);
        const float h2 = h * h;
        const float h_inv = 1.f / h;
        const float h_inv_3 = h_inv * h_inv * h_inv;

        float f_ij, pot_ij;

        if (use_full) {
          iact_grav_pp_full(r2, h2, h_inv, h_inv_3, mass_j, &f_ij, &pot_ij);
        } else {
          iact_grav_pp_truncated(
              r2, h2, h_inv, h_inv_3, mass_j, r_s_inv, &f_ij, &pot_ij);
        }

        a_x += f_ij * dx;
        a_y += f_ij * dy;
        a_z += f_ij * dz;
        pot += pot_ij;
      }
    }

    __syncthreads();
  }

  if (valid_target) {
	  const int out = active_base + active_slot;
	  gravity_gpu_values_recv_d[out].values_i.x = a_x * factor;
	  gravity_gpu_values_recv_d[out].values_i.y = a_y * factor;
	  gravity_gpu_values_recv_d[out].values_i.z = a_z * factor;
	  gravity_gpu_values_recv_d[out].values_i.w = pot * factor;
 }
}
/**
 * @brief Compute direct pair-cell P-P gravity interactions for one side of each packed pair.
 *
 * Each block processes one packed cell pair and accumulates the force and
 * potential on either the i-side or j-side particles, depending on swap.
 *
 * @param send Device input buffer for packed particle pairs.
 * @param recv Device output buffer for accelerations and potential.
 * @param periodic Whether periodic boundary conditions are enabled.
 * @param r_s_inv Inverse splitting scale for truncated periodic forces.
 * @param symmetric Whether both sides of the pair are updated.
 * @param swap Selects which side of the packed pair is updated.
 * @param dim_0 Domain size in the x dimension.
 * @param dim_1 Domain size in the y dimension.
 * @param dim_2 Domain size in the z dimension.
 * @param max_cell_size Maximum number of particles per packed cell.
 * @param ncells Number of packed cell slots in the batch.
 */
__global__ void pair_grav_pp_kernel(
    const gravity_gpu_values_send *send,
    gravity_gpu_values_recv *recv,
    int periodic, float r_s_inv,
    int symmetric,
    int swap, // 0: compute i-side (base_i interacts with base_j) 1: compute j-side (base_j interacts with base_i)
    float dim_0, float dim_1, float dim_2,
    int max_cell_size, int ncells){
    
  int pair_id = blockIdx.x;
  int base0 = (2 * pair_id) * max_cell_size;
  int base1 = base0 + max_cell_size;

  int base_i = swap ? base1 : base0;
  int base_j = swap ? base0 : base1;

  int count_i = send[base_i].flags0.z;
  int count_j = send[base_j].flags0.z;

  int pid = blockIdx.y * blockDim.x + threadIdx.x;
  if (pid >= count_i) return;

  // Only update if this target cell is active (matches CPU)
  int ci_active = send[base_i].flags0.w;
  if (!ci_active) return;

  // active particle gating
  int act = (send[base_i + pid].flags0.x > 0);
  if (!act) return;

  float xi = send[base_i + pid].values_i.x;
  float yi = send[base_i + pid].values_i.y;
  float zi = send[base_i + pid].values_i.z;
  float hi = send[base_i + pid].values_i.w;

  float ax=0.f, ay=0.f, az=0.f, pot=0.f;

  int use_full = send[base_i].flags1.x;   // 1 full, 0 truncated

  for (int pjd = 0; pjd < count_j; ++pjd) {

    float xj = send[base_j + pjd].values_i.x;
    float yj = send[base_j + pjd].values_i.y;
    float zj = send[base_j + pjd].values_i.z;
    float mj = send[base_j + pjd].mass.x; 

    float dx = xj - xi;
    float dy = yj - yi;
    float dz = zj - zi;

    if (periodic) {
      dx = nearestf1(dx, dim_0);
      dy = nearestf1(dy, dim_1);
      dz = nearestf1(dz, dim_2);
    }

    float r2 = dx*dx + dy*dy + dz*dz;

    float hj = send[base_j + pjd].values_i.w;
    float h = max(hi, hj);
    float h2 = h*h;
    float hinv = 1.f / h;
    float hinv3 = hinv*hinv*hinv;

    float fij, potij;
    if (use_full) {
      iact_grav_pp_full(r2, h2, hinv, hinv3, mj, &fij, &potij);
    } else {
      iact_grav_pp_truncated(r2, h2, hinv, hinv3, mj, r_s_inv, &fij, &potij);
    }

    ax += fij * dx;
    ay += fij * dy;
    az += fij * dz;
    pot += potij;
  }

  recv[base_i + pid].values_i.x += ax;
  recv[base_i + pid].values_i.y += ay;
  recv[base_i + pid].values_i.z += az;
  recv[base_i + pid].values_i.w += pot;
}

/**
 * @brief Compute tiled direct pair-cell P-P gravity interactions for one side of each packed pair.
 *
 * This kernel is the shared-memory tiled variant of @ref pair_grav_pp_kernel,
 * loading source-particle data in tiles to reduce global memory traffic.
 *
 * @param send Device input buffer for packed particle pairs.
 * @param recv Device output buffer for accelerations and potential.
 * @param periodic Whether periodic boundary conditions are enabled.
 * @param r_s_inv Inverse splitting scale for truncated periodic forces.
 * @param symmetric Whether both sides of the pair are updated.
 * @param swap Selects which side of the packed pair is updated.
 * @param dim_0 Domain size in the x dimension.
 * @param dim_1 Domain size in the y dimension.
 * @param dim_2 Domain size in the z dimension.
 * @param max_cell_size Maximum number of particles per packed cell.
 * @param ncells Number of packed cell slots in the batch.
 */
__global__ void pair_grav_pp_kernel_tiled(
    const gravity_gpu_values_send *send,
    const float4 *send_pos_mass,
    const float *send_h,
    gravity_gpu_values_recv *recv,
    const int *pair_counts_d,
    const int *pair_offsets_d,
    const int *pair_active_counts_d,
    const int *pair_active_offsets_d,
    const int *pair_active_index_d,
    int periodic, float r_s_inv,
    int swap,
    float dim_0, float dim_1, float dim_2,
    int ncells) {

  int pair_id = blockIdx.x;
  int slot0 = 2 * pair_id;
  int slot1 = slot0 + 1;
  
  if (slot1 >= ncells) return;

  int base0 = pair_offsets_d[slot0];
  int base1 = pair_offsets_d[slot1];

  int base_i = swap ? base1 : base0;
  int base_j = swap ? base0 : base1;

  int count_i = swap ? pair_counts_d[slot1] : pair_counts_d[slot0];
  int count_j = swap ? pair_counts_d[slot0] : pair_counts_d[slot1];

  int pid = blockIdx.y * blockDim.x + threadIdx.x;
  const int target_slot = swap ? slot1 : slot0;
  const int active_count_i = pair_active_counts_d[target_slot];
  if (active_count_i <= 0) return;
  int valid_pid = (pid < active_count_i);

  int ci_active = send[base_i].flags0.w;
  if (!ci_active) return;

  const int active_base = pair_active_offsets_d[target_slot];
  const int local_pid_i =
    valid_pid ? pair_active_index_d[active_base + pid] : 0;

  float xi = 0.f;
  float yi = 0.f;
  float zi = 0.f;
  float hi = 0.f;

  if (valid_pid) {
    xi = send[base_i + local_pid_i].values_i.x;
    yi = send[base_i + local_pid_i].values_i.y;
    zi = send[base_i + local_pid_i].values_i.z;
    hi = send[base_i + local_pid_i].values_i.w;
  }

  float ax = 0.f, ay = 0.f, az = 0.f, pot = 0.f;

  int use_full = send[base_i].flags1.x;

  //extern __shared__ gravity_gpu_values_send sh_j[];
  extern __shared__ char smem[];

	float4 *sh_pos_mass = (float4*)smem;
	float *sh_h = (float*)&sh_pos_mass[blockDim.x];

	for (int j0 = 0; j0 < count_j; j0 += blockDim.x) {

	  int jload = j0 + threadIdx.x;

	  if (jload < count_j) {
	    sh_pos_mass[threadIdx.x] = send_pos_mass[base_j + jload];
	    sh_h[threadIdx.x] = send_h[base_j + jload];
	  }

	  __syncthreads();

	  int tile = min(blockDim.x, count_j - j0);

	  if (valid_pid) {
	    for (int j = 0; j < tile; ++j) {
	      float4 pj = sh_pos_mass[j];

		float xj = pj.x;
		float yj = pj.y;
		float zj = pj.z;
		float mj = pj.w;

		float hj = sh_h[j];

        float dx = xj - xi;
        float dy = yj - yi;
        float dz = zj - zi;

        if (periodic) {
          dx = nearestf1(dx, dim_0);
          dy = nearestf1(dy, dim_1);
          dz = nearestf1(dz, dim_2);
        }

        float r2 = dx * dx + dy * dy + dz * dz;

        //float hj = pj.values_i.w;
        float h = max(hi, hj);
        float h2 = h * h;
        float hinv = 1.f / h;
        float hinv3 = hinv * hinv * hinv;

        float fij, potij;
        if (use_full) {
          iact_grav_pp_full(r2, h2, hinv, hinv3, mj, &fij, &potij);
        } else {
          iact_grav_pp_truncated(r2, h2, hinv, hinv3, mj, r_s_inv, &fij, &potij);
        }

        ax += fij * dx;
        ay += fij * dy;
        az += fij * dz;
        pot += potij;
      }
    }
    __syncthreads();
  }

  if (valid_pid) {
    const int out = active_base + pid;

	recv[out].values_i.x = ax;
	recv[out].values_i.y = ay;
	recv[out].values_i.z = az;
	recv[out].values_i.w = pot;;
  }
}
